# Generated by Django 5.1.6 on 2025-03-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_donation_amount_alter_donation_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
