# Generated by Django 5.1.6 on 2025-03-05 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_project_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_selected',
        ),
        migrations.CreateModel(
            name='SelectedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.project')),
            ],
        ),
    ]
