# Generated by Django 5.1.6 on 2025-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_remove_project_image_projectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ratings',
            field=models.JSONField(default=list),
        ),
    ]
